cache: yarn
install:
  - gem install sass # for theme builder using grunt sass
script:
  - yarn
  - (cd packages/angular-skyhook && yarn run build)
  - (cd packages/angular-skyhook-card-list && yarn run build)
  - (cd packages/angular-skyhook-multi-backend && yarn run build)
after_success:
  - yarn run lerna bootstrap
  - bash ./build-docs.sh --travis
deploy:
  provider:     pages
  skip_cleanup: true
  local_dir:    out-docs
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
